config/routes.rb
Aride::Application.routes.draw do

  devise_for :users

  resources :journeys

  get "main/index"
  
  root :to=>"journeys#index"

end

app/models/journey.rb
class Journey < ActiveRecord::Base

  has_many :ride_requests
  belongs_to :user
  
  before_save :generate_travel_time

  def generate_travel_time
    self.travel_time = self.travel_stamp.to_i
  end
  
  def possible_matches
    t_time = self.travel_time

    from_time = t_time - 3600
    to_time = t_time + 3600
    jid = self.id
    #Journey.find (:all,:conditions => {:travel_time => from_time..to_time})
    
    direction = self.direction
    
    Journey.find(:all, :conditions => ["travel_time > ? AND travel_time < ? AND direction == ? AND id != ?", from_time, to_time, direction, jid])
  end

end

app/models/ride_request.rb
class RideRequest < ActiveRecord::Base
  
  belongs_to :journey

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable #, :validatable

  # Setup accessible (or protected) attributes for your model
  
  has_many :journeys
  
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def truncated_email
    t = self.email.split "@"
    u = t[0]
    if u.length > 3
      dirty_name = u[0..2] + "..."
    else
      dirty_name = u + "..."
    end
    dirty_name + '@' + t[1]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  #helper_method :current_user
  helper_method :auth_user
  #helper_method :user_logged_in?

  private

=begin
  def current_user
    # NOTE: This is because we have to check is the user exists.
    # Encountered an error when the session is valid but a db:reset
    # had been done :)
    if session[:user_id] and User.exists? session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def user_logged_in?
    return true unless @current_user.nil?
    return false
  end
=end

  def auth_user
    unless current_user
      if request.xhr?
        render :json => "not authorized", :status => :unprocessable_entity
      else
        redirect_to root_url
      end
    end
  end

end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  
  before_filter :check_login
  before_filter :auth_user, :only => :request_ride
  before_filter :owned_by_user?, :only =>[:edit, :destroy, :update]
  
  # GET /journeys
  # GET /journeys.json
  def index
    @journeys = Journey.where(:user_id=>current_user.id).order("created_at desc").limit(10)
    #@journeys = Journey.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @journeys }
    end
  end

  # GET /journeys/1
  # GET /journeys/1.json
  def show
  
    if params[:request_to_ride]
      from_id = params[:id]
      to_id = params[:request_to_ride]
          
      @journeys = Journey.where(:id=>[from_id,to_id])
      @ride_request_check = RideRequest.where(:journey_id=>from_id)
  
      if @journeys.empty?
        flash[:notice] = "Ride request failed"
      elsif @journeys.length==2 and (@ride_request_check.length==0)
        @ride_request = RideRequest.new(:journey_id=>from_id, :for_journey_id=>to_id)
        if @ride_request.save
          flash[:notice] = "Ride request sent"
        else
          flash[:notice] = "Ride request failed"
        end
      end 
    end
    
    @journey = Journey.find(params[:id])

    #TODO add another field. delete this complex calculation
    #TODO if the journey belongs to the user, then render, else throw error
    
    @matches = @journey.possible_matches
    
    @sent_requests = []
    
    @matches.each do |m|
      if @journey.ride_requests.where(:for_journey_id => m.id).length == 1
        @sent_requests.push m.id
      end
    end
    
    # if json, you'll need @possible_matches and @journey in hash
  
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: {journey: @journey, possible_matches: @possible_matches} }
    end
  end
  
  def request_ride
    from_id = params[:from_id]
    to_id = params[:to_id]
        
    @journeys = Journey.where(:id=>[from_id,to_id])
    @request_ride_check = RideRequest.where(:journey_id=>from_id)

    if @journeys.empty?
      # then don't do anything bob
      render json: {:error=>"empty"}
    elsif @journeys.length==2 and (@ride_request_check.length==0)
      @ride_request = RideRequest.new(:journey_id=>from_id, :to_id=>to_id)
      if @ride_request.save
        render json: {:msg=>"added"}
      else
        render json: {:msg=>"empty"}
      end
    end    
  end

  def new
    @journey = Journey.new
    @journey.travel_time = DateTime.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @journey }
    end
  end

  # GET /journeys/1/edit
  def edit
  end

  # POST /journeys
  # POST /journeys.json
  def create
    @journey = Journey.new(params[:journey])
    @journey.user_id = current_user.id

    respond_to do |format|
      if @journey.save
        format.html { redirect_to root_path, notice: 'Journey was successfully created.' }
        format.json { render json: @journey, status: :created, location: @journey }
      else
        format.html { render action: "new" }
        format.json { render json: @journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /journeys/1
  # PUT /journeys/1.json
  def update

    respond_to do |format|
      if @journey.update_attributes(params[:journey])
        format.html { redirect_to @journey, notice: 'Journey was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { 
          render json: {errors: @journey.errors, status: :unprocessable_entity}
        }
      end
    end
  end

  # DELETE /journeys/1
  # DELETE /journeys/1.json
  def destroy
    @journey.destroy

    respond_to do |format|
      format.html { redirect_to journeys_url }
      format.json { head :ok }
    end
  end
  
  private
  
  def owned_by_user?
    @journey = Journey.find(params[:id])
    if @journey.user_id != current_user.id
      redirect_to root_url
    end
  end
  
  def check_login
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end
end 

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/journeys/_form.html.haml
= form_for @journey do |f|
  -if @journey.errors.any?
    #error_explanation
      %h2= "#{pluralize(@journey.errors.count, "error")} prohibited this journey from being saved:"
      %ul
        - @journey.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :travel_time
    = f.datetime_select :travel_stamp
  .field
    = f.label :place
    = f.text_field :place
  .field
    = f.label :direction
    = f.select :direction, options_for_select([["from airport","from"], ["to airport", "to"]]), :selected => f.object.direction
  .actions
    = f.submit 'Save'

app/views/journeys/edit.html.haml
%h1 Editing journey

= render 'form'

= link_to 'Show', @journey
\|
= link_to 'Back', journeys_path

app/views/journeys/index.html.haml
- if user_signed_in?

  -if @journeys.length != 0

    %h1 Listing journeys
    
    %table
      %tr
        %th Travel time
        %th Place
        %th People
        %th
        %th
        %th
    
      - @journeys.each do |journey|
        - link_label = journey.possible_matches.length.to_s + " people"
        %tr
          %td= journey.travel_stamp.to_s :short
          %td= journey.place
          %td= link_to link_label, journey
          %td= link_to 'Edit', edit_journey_path(journey)
          %td= link_to 'Destroy', journey, :confirm => 'Are you sure?', :method => :delete
    -else
      no journeys found bob!
      
  %br
  
  = link_to 'New Journey', new_journey_path
-else
  not logged in dude

app/views/journeys/new.html.haml
%h1 New journey

= render 'form'

= link_to 'Back', journeys_path

app/views/journeys/show.html.haml
%div{:class=>"row journey"}
  %div{:class=>"column journey"}

%p
  %b Travel time:
  = @journey.travel_stamp.to_s :short
%p
  %b Place:
  = @journey.place

- @matches.each do |m|
  %p
    = m.user.truncated_email
    - unless @sent_requests.include?(m.id)
      = puts m.id
      = link_to "Request to ride", "/journeys/"+@journey.id.to_s+"/?request_to_ride="+m.id.to_s
    -else
      [Request has already been sent]
    
= link_to 'Edit', edit_journey_path(@journey)
\|
= link_to 'Back', journeys_path

app/views/layouts/application.haml
!!!
%html
  %head
    %title Aride
    = stylesheet_link_tag    "grid"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = javascript_include_tag "main"
    = csrf_meta_tags

  %body
    .wrapper
      .user_info

      .header
        - if current_user
          = current_user.email
          \-
          = link_to "Sign out", destroy_user_session_path
        - else
          = link_to "Sign in", new_user_session_path
          |
          = link_to "Sign up", new_user_registration_path

      -if notice
        .notice
          =notice

      .content
        = yield

      .footer

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>